### ISSUE TITLE
关于 #(reply, portrait, nameshow) :  msg

### ISSUE THREAD

**Issue by shithappens2016** [Aobanana-chan/Tiebanana#2]
你好

`回复 #(reply, portrait, nameshow) :  msg` 
这个格式似乎不能达到效果。你能再测试一下吗？

**Comment by Aobanana-chan** [comment]
刚测试了一下，是正常可用的。
请具体说明你的用法，或贴上关键部分的代码。
（建议使用contentBuilder去构建这个）

**Comment by shithappens2016** [comment]
比方说，回复帖子([https://tieba.baidu.com/p/7161771681](https://tieba.baidu.com/p/7161771681))五楼的 `耍耍学生`
根据`contentBuilder`构造出来的字符串是：`#(reply, tb.1.c91fb89b.Z4iLfwWTk-vAaAdtHDhxaQ, 耍耍学生) : 消息`
结果，回复是发出去了，不过，贴吧直接显示了这段字符串本身，而不是`某某 回复 耍耍学生：消息 `。

**Comment by Aobanana-chan** [comment]
replyUID这个参数填了吗

**Comment by shithappens2016** [comment]
> replyUID这个参数填了吗
填了，麻烦看下这2个参数有没有问题
content: `回复 #(reply, tb.1.c91fb89b.Z4iLfwWTk-vAaAdtHDhxaQ, 耍耍学生) : 消息`
replyUID: `'884857738'`

**Comment by Aobanana-chan** [comment]
content：`回复 #(reply, tb.1.c91fb89b.Z4iLfwWTk-vAaAdtHDhxaQ?t=1607501158, 耍耍学生) :消息`
replyUID：`884857738`
kw：`机械革命`
fid：`13607742`
floorId：`137137648527`

portrait不一样，但不知道有无影响（估计没有，最重要的参数还是replyUID）这个问题没法复现，也不清楚是什么原因。
你是个人项目引用API出问题还是你用tiebanana就有这个问题？

**Comment by shithappens2016** [comment]
你好，问题解决了。原来百度会根据 "_client_type" "_client_version" "_phone_imei" 来判断这个格式是否有效 。
