### ISSUE TITLE
关于 _client_type _client_version _phone_imei

### ISSUE THREAD

**Issue by shithappens2016** [Aobanana-chan/Tiebanana#3]
你好，根据这个古老的脚本([https://userscripts-mirror.org/scripts/review/177032](https://userscripts-mirror.org/scripts/review/177032))得知：`_client_type = 1` 表示客端是 `iphone` 。我试了下，单单把`_client_type`设成`1`**无法**让贴吧将客户端识别成`iphone`。 烦请指教。

**Comment by Aobanana-chan** [comment]
没有iPhone，无法解答，这个建议自己抓包/解包分析。
