### ISSUE TITLE
贴吧lite作者弃坑了

### ISSUE THREAD

**Issue by H357753** [Aobanana-chan/Tiebanana#4]
大佬要不要接一下贴吧lite或者继续做这个项目

**Comment by Aobanana-chan** [comment]
我是想继续的, 但和贴吧lite那边的情况差不多
1. 没那么多的时间维护, 大多时间都花在API的逆向上, 但贴吧的那边更新的频率太高了, 成本确实很高, 结果就是现在UI是个半成品, API时间久了有些用不了,导致功能失效
2. 担心API的滥用, 之前有过类似的issue跳脸了
于是我在想API部分不开源,并全部重写,然后就得花上大量时间, 但是没这么多时间, 就这么一直鸽这了

**Comment by H357753** [comment]
好的感谢大佬回答，不知道这个第三方这么困难。开源项目只能靠爱发电，没动力做太正常了。

**Comment by n0099** [comment]
https://github.com/Starry-OvO/aiotieba/issues/168

> 2. 担心API的滥用, 之前有过类似的issue跳脸了

而`贴吧辅助工具头子鸡血神` @bakasnow 对此也早有预言 https://tieba.baidu.com/p/8426862419?pid=147693358045#147693358045 https://web.archive.org/web/20230603135354/https://tieba.baidu.com/p/8426862419

**Comment by Aobanana-chan** [comment]
总结一下吧:
1. 项目会继续, 但什么时候重启还是未知数, 至少4月份之前是不会动的。
2. 若继续, 拆分当前项目, UI开源, API部分闭源, 并且API部分大概率会全部重写, 对整个项目结构会有很大的变动
---
其实更新频率变低了主要是我自己够用, 然后越逆越觉得贴吧那边的接口是粪坑, 充满了各种重复和无用的数据, 同样的东西都会有好几套, 我真想知道官方自己看这些数据蒙不蒙
